// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheCardMin: typeof import('./src/components/TheCardMin.vue')['default']
    TheFooter: typeof import('./src/components/TheFooter.vue')['default']
    TheHeaterExample: typeof import('./src/components/TheHeaterExample.vue')['default']
    TheInput: typeof import('./src/components/TheInput.vue')['default']
    TheNavbar: typeof import('./src/components/TheNavbar.vue')['default']
    ThePostCalcTable: typeof import('./src/components/ThePostCalcTable.vue')['default']
    ThePreCalcTable: typeof import('./src/components/ThePreCalcTable.vue')['default']
  }
}
